name: brevet
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - spyder
  - seaborn
  - xgboost
  - pip:
      - ramp-workflow
      - geopandas
      - folium
