name: ramp-brevet
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - geopandas
  - folium
  - pip:
      - ramp-workflow
